/**
 * Recovery Key System - FAZ 7: Zero-Knowledge Password Recovery
 * 
 * Simplified version for initial production release.
 * Generates BIP39 24-word mnemonic for recovery.
 * 
 * Full recovery flow will be implemented in future phase.
 */

import * as bip39 from "bip39";

/**
 * Generate 24-word mnemonic (256-bit entropy)
 * BIP39 standard - same as crypto wallets
 */
export function generateRecoveryMnemonic(): string {
  // Generate 256 bits (32 bytes) of entropy using Web Crypto API
  const entropy = new Uint8Array(32);
  if (typeof window !== "undefined" && window.crypto) {
    window.crypto.getRandomValues(entropy);
  } else {
    throw new Error("Web Crypto API not available");
  }
  
  // Convert to hex string
  const entropyHex = Array.from(entropy)
    .map(b => b.toString(16).padStart(2, '0'))
    .join('');
  
  // Convert to BIP39 mnemonic (24 words)
  const mnemonic = bip39.entropyToMnemonic(entropyHex);
  
  return mnemonic;
}

/**
 * Validate mnemonic (checksum verification)
 */
export function validateRecoveryMnemonic(mnemonic: string): boolean {
  return bip39.validateMnemonic(mnemonic);
}

/**
 * Generate Recovery PDF/Text (for printing)
 * User should print and store securely
 */
export function generateRecoveryPDF(
  mnemonic: string,
  userEmail: string
): string {
  const words = mnemonic.split(" ");
  
  return `
OneCloud Recovery Key
Generated: ${new Date().toISOString()}
Account: ${userEmail}

⚠️ CRITICAL: Save this recovery key securely!
- Store offline (printed, encrypted password manager)
- NEVER share with anyone (including OneCloud support)
- Without this key, lost password = lost data forever

Recovery Words (24):
${words.map((word, i) => `${(i + 1).toString().padStart(2, "0")}. ${word}`).join("\n")}

Recovery Instructions:
1. Go to onecloud.com/recover
2. Enter your email and these 24 words IN ORDER
3. Set new password
4. Access your encrypted files

Security Notice:
- OneCloud uses zero-knowledge encryption
- We CANNOT recover your password or files
- This recovery key is your ONLY backup
- Treat it like a bank vault key

Generated by OneCloud - Zero-Knowledge Cloud Storage
  `.trim();
}
